id: P5DABF371
initial_creation_type: input
source_metadata:
  title: Fire Offering Series
  language: bo
  description: 'Texts related to the ritual of fire offering (homa; sbyin sreg/me
    mchod):'
  volume:
    808a7be7ea764281b1ae254f6ea8469f:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Practices
    21f15652c60e4f93adadd65357e12eb7:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Practices
    4445c87c6fe944d0aea7236c998c5218:
      title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for
        the ''Neck-Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Practices
    05f75634252e4e0c92f206df4a2c86a8:
      title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
      parent: Practices
created_at: '2022-03-01T03:41:22.826619'
last_modified_at: '2022-03-01T03:41:22.826622'
